CREATE DATABASE beanlog WITH owner postgres;

REVOKE CONNECT ON DATABASE beanlog FROM PUBLIC;

CREATE ROLE beanlog LOGIN PASSWORD 'DONTLOOKHERE';

ALTER USER beanlog WITH PASSWORD ?;

GRANT CONNECT ON DATABASE beanlog TO beanlog;